services:
  webserver:
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    working_dir: /var/www
    volumes:
      #Logs
      - ./docker/log/applications:/var/log
      - ./check24-backend-test:/var/www/check24-backend-test
      #Virtual Hosts
      - ./docker/webserver/vhosts/vhost.conf:/opt/docker/etc/httpd/vhost.conf
      - ./docker/webserver/vhosts/check24-backend-test.conf:/opt/docker/etc/httpd/vhost.common.d/check24-backend-test.conf
    environment:
      - PHP_XDEBUG_ENABLED=0
      - XDEBUG_MODE=off
      - XDEBUG_START_WITH_REQUEST=no
      - PHP_IDE_CONFIG=serverName=check24_backend_test.local
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER=composer.json
    extra_hosts:
      - check24-backend-test.local:127.0.0.1
    links:
      - database
    ports:
      - 80:80
      - 443:443
      - 9001:9001
    networks:
      back-network:
        ipv4_address: 172.192.0.2

  database:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
      - ./docker/database/bootstrap:/docker-entrypoint-initdb.d
      - ./docker/database/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./docker/database/log/general.log:/var/log/mysql/general.log
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      back-network:
        ipv4_address: 172.192.0.4

networks:
  back-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.192.0.0/16