security:
    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true

    access_control:
        - { path: ^/api/*, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
